services:
  web:
    build:
      context: .
    volumes:
      - ./web_application:/web
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: on-failure
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5435:5432"
    restart: on-failure

