# Generated by Django 5.1.1 on 2024-10-08 09:17

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='user/profile_photos/')),
                ('location', django_countries.fields.CountryField(max_length=2, verbose_name='Choose your location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=80)),
                ('bio', models.TextField()),
                ('website_url', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'db_table': 'client_profile',
                'ordering': ['id'],
            },
        ),
    ]
