# Generated by Django 5.1.1 on 2024-10-08 09:17

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='user/profile_photos/')),
                ('location', django_countries.fields.CountryField(max_length=2, verbose_name='Choose your location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('trainee', 'Trainee'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20)),
                ('skills', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('portfolio_url', models.URLField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profiles',
                'db_table': 'freelancer_profile',
                'ordering': ['id'],
            },
        ),
    ]
