# Generated by Django 5.1 on 2024-08-20 13:45

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('level', models.CharField(choices=[('trainee', 'Trainee'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=20)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profiles',
                'db_table': 'freelancer_profile',
                'ordering': ['id'],
            },
        ),
    ]
