# Generated by Django 5.1 on 2024-08-16 12:40

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('level', models.CharField(
                    choices=[('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')],
                    max_length=7)),
                ('skills', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_freelancer', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False))
            ],
            options={
                'db_table': 'freelancer_profile',
            },
        ),
    ]
